<?php

namespace backend\assets;

use yii\web\AssetBundle;
use yii;
use common\models\Config;
/**
 * Main backend application asset bundle.
 */
class AppAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $res = Config::findOne(['config_key' => 'resource_version']);
        $value = $res ? $res->config_value : '1.0';
        Yii::$app->params['r_ver'] = '?v=' . $value;
    }

    public $css = [
        'bootstrap/css/bootstrap.min.css',
        'css/font-awesome.min.css',
        'css/animate.css',
        'css/style.css',
    ];
    
    public $js = [
        'scripts/jquery.min.js',
        'scripts/bootstrap.min.js',
        'scripts/plugins/metisMenu/jquery.metisMenu.js',
        'scripts/plugins/slimscroll/jquery.slimscroll.min.js',
        'scripts/plugins/layer/layer.min.js',
    ];
    public $depends = [
        'yii\web\YiiAsset',
        'backend\assets\IEhack'
    ];

    //定义按需加载css方法，注意加载顺序在最后
    public static function addCss($view, $cssfile)
    {
        $view->registerCssFile($cssfile, [AppAsset::className(), 'depends' => 'backend\assets\AppAsset']);
    }
    //定义按需加载JS方法，注意加载顺序在最后
    public static function addScript($view, $jsfile)
    {
        $view->registerJsFile($jsfile, [AppAsset::className(), 'depends' => 'backend\assets\AppAsset']);
    }
}
