<?php
//                              _(\_/)
//                             ,((((^`\         //+--------------------------------------------------------------
//                            ((((  (6 \        //|Copyright (c) 2017 http://www.shuwon.com All rights reserved.
//                          ,((((( ,    \       //+--------------------------------------------------------------
//      ,,,_              ,(((((  /"._  ,`,     //|Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
//     ((((\\ ,...       ,((((   /    `-.-'     //+--------------------------------------------------------------
//     )))  ;'    `"'"'""((((   (               //|Author: xww < xww@wyw1.cn >
//    (((  /            (((      \              //+--------------------------------------------------------------
//     )) |                      |
//    ((  |        .       '     |
//    ))  \     _ '      `t   ,.')
//    (   |   y;- -,-""'"-.\   \/
//    )   / ./  ) /         `\  \
//       |./   ( (           / /'                __     __
//       ||     \\          //'|                /  \~~~/  \
//       ||      \\       _//'||          ,----(     ..    )
//       ||       ))     |_/  ||         /      \__     __/
//       \_\     |_/          ||       /|         (\  |(
//       `'"                  \_\     ^ \   /___\  /\ |
//                            `'"        |__|   |__|-"
namespace frontend\controllers;
use common\models\Img;
use common\models\News;
use common\models\Single;
use common\models\Team;
use Yii;
use yii\helpers\VarDumper;


/**
 * 关于我们
 * @author 制作人
 * @since 1.0
 */
class AboutController extends CommonController {

    public function beforeAction($action)
    {
      parent::beforeAction($action); // TODO: Change the autogenerated stub
      $this->getSeo(2);
        return true;
    }


    public function actionIndex(){
        $data['single'] = Single::findOne(['type'=>'about']);
        $data['title'] = '单位简介';
        $this->getView()->params['isActive']='about';
        return $this->render('framework',$data);

    }


    public function actionFramework(){

        $data['single'] = Single::findOne(['type'=>'organization']);
        $data['title'] = '组织机构';
        $this->getView()->params['isActive']='framework';
	    return $this->render('framework',$data);
    }

    public function actionCertificate(){

        $data['list'] = Img::find()->where(['img_type'=>'certificate','enabled'=>1])->all();
        $data['title'] = '资质证书';
        $this->getView()->params['isActive']='certificate';
        return $this->render('certificate',$data);
    }

    public function actionDuties(){
        $data['single'] = Single::findOne(['type'=>'duties']);
        $data['title'] = '单位职能';
        $this->getView()->params['isActive']='duties';
        return $this->render('framework',$data);
    }


    public function actionLeaders(){
        $data['list'] = Team::find()->where(['img_type'=>'team','enabled'=>1])->orderBy(['sort'=>SORT_DESC,'img_id'=>SORT_DESC])->all();
        $this->getView()->params['isActive']='leaders';
        $data['title'] = '领导班子';
        return $this->render('leaders',$data);
    }

    public function actionMemorabilia(){
        $data['single'] = Single::findOne(['type'=>'events']);
        $this->getView()->params['isActive']='memorabilia';
        $data['title'] = '大事记';
        return $this->render('framework',$data);
    }
    public function actionPost(){
        $data['single'] = Single::findOne(['type'=>'post-setting']);
        $this->getView()->params['isActive']='post';
        $data['title'] = '岗位设置';
        return $this->render('framework',$data);
    }
    public function actionStatistical(){
        $data['single'] = Single::findOne(['type'=>'statistical-information']);
        $data['title'] = '统计信息';
        $this->getView()->params['isActive']='post';
        return $this->render('framework',$data);
    }

}