<?php

namespace frontend\assets;

use yii;
use common\models\Config;
use yii\debug\models\search\Db;
use yii\web\AssetBundle;

/**
 * Main frontend application asset bundle.
 */
class AppAsset extends AssetBundle
{


    public $basePath = '@webroot';
    public $baseUrl = '@web';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $res = Config::findOne(['config_key' => 'resource_version']);
        $value = $res ? $res->config_value : '1.0';
        Yii::$app->params['r_ver'] = '?v=' . $value;
        //Yii::$app->params['ver'] = '';
    }

    public $css = [
        '/static/assets/lib/style/common.css',
        '/static/assets/style/main.shuwon.css',
    ];
    public $js = [
        '/static/assets/lib/js/jquery-1.10.1.min.js',
        '/static/assets/lib/js/modernizr.js',
        '/static/assets/lib/js/tool.min.js',
        '/static/assets/js/main.shuwon.js',
    ];

    public $depends = [
//      'yii\web\YiiAsset',
//      'yii\bootstrap\BootstrapAsset',
    ];

    //定义按需加载css方法，注意加载顺序在最后
    public static function addCss($view, $cssfile)
    {
        $view->registerCssFile($cssfile, [AppAsset::className(), 'depends' => 'frontend\assets\AppAsset']);
    }
    //定义按需加载JS方法，注意加载顺序在最后
    public static function addScript($view, $jsfile)
    {
        $view->registerJsFile($jsfile, [AppAsset::className(), 'depends' => 'frontend\assets\AppAsset']);
    }
}
